<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="BusinessDataLogic\**" />
    <Compile Remove="PVBBusinessLogic\**" />
    <Compile Remove="PVBDataLogic\**" />
    <Compile Remove="VocabularyCommon\**" />
    <EmbeddedResource Remove="BusinessDataLogic\**" />
    <EmbeddedResource Remove="PVBBusinessLogic\**" />
    <EmbeddedResource Remove="PVBDataLogic\**" />
    <EmbeddedResource Remove="VocabularyCommon\**" />
    <None Remove="BusinessDataLogic\**" />
    <None Remove="PVBBusinessLogic\**" />
    <None Remove="PVBDataLogic\**" />
    <None Remove="VocabularyCommon\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="PVBBusinessLogic\PVBBusinessLogic.csproj" />
  </ItemGroup>

</Project>
