<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="MimeKit" Version="4.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PVBDataLogic\PVBDataLogic.csproj" />
    <ProjectReference Include="..\VocabularyCommon\VocabularyCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Email">
      <HintPath>..\Email\Email\bin\Debug\net8.0\Email.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
